name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x  # Use Node.js 16.x or later

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@12.5.2

      - name: Set up Firebase
        run: |
          # Authenticate with Firebase (you might need to replace the command with your own authentication method)
          firebase login:ci --interactive
          echo "Firebase authenticated successfully."

      - name: Build React App
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --project portfolio-website-60ee2 --token $FIREBASE_TOKEN
